name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: run build
        run: |
          echo "running the build.. "
          echo "ensure to add code to build .. "
